version: "3.9"

services:
  node:
    container_name: node
    build:
      context: ./Docker/node
    ports:
      - 3000:3000
    volumes:
      - ./src:/home/node/node_hobbys/src
    environment:
      - NODE_ENV=development
    command: yarn init && yarn install --frozen-lockfile
    # working_dir: /home/node/node_hobbys
    stdin_open: true
    tty: true

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    working_dir: /home/node/node_hobbys/src
    volumes:
      - ./postgres-data:/var/lib/postgres/data
    ports:
      - 5432:5432

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/nginx:/var/log/nginx
      - ./nginx:/var/www/html
