version: "3.9"

services:
  node:
    container_name: node
    build:
      context: ./Docker/node
    ports:
      - 3000:3000
      - 4000:4000
    volumes:
      - ./src:/home/node/node_hobbys/src
    environment:
      - NODE_ENV=development
    command: yarn init && yarn install --frozen-lockfile
    stdin_open: true
    tty: true

  mysql:
    container_name: express_mysql
    build: ./Docker/mysql
    ports:
      - 3306:3306
    volumes:
      - node-db-volume:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: express_db

  nginx:
    image: nginx:latest
    container_name: express_nginx
    ports:
      - 443:443
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/nginx:/var/log/nginx
      - ./nginx:/var/www/html

volumes:
  node-db-volume:
