version: "3.9"

services:
  app:
    container_name: node_container
    build:
      context: ./.docker/node
    ports:
      - 3000:3000
      - 4000:4000
    volumes:
      - ./src:/home/node/node_hobbys/src
    environment:
      - NODE_ENV=development
    # command: yarn init && yarn install --frozen-lockfile
    stdin_open: true
    tty: true

  mysql:
    container_name: node_mysql
    build: ./.docker/mysql
    ports:
      - 3306:3306
    volumes:
      - node-db-volume:/var/lib/mysql
      # - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: express_db

volumes:
  node-db-volume:
